platform :ios, '5.0'
inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'

target 'Luhn Algorithm (Mod 10)' do #, :exclusive => true do
  pod 'ObjectiveLuhn', :path => '../ObjectiveLuhn.podspec'
end

target :Tests do #:exclusive => true do
  pod 'Kiwi'
end
